Added nginx layer

diff --git a/dehydrated-cf-nginx/Dockerfile b/dehydrated-cf-nginx/Dockerfile
--- a/dehydrated-cf-nginx/Dockerfile
+++ b/dehydrated-cf-nginx/Dockerfile
@@ -1,18 +1,31 @@
 FROM lycofron/dehydrated-cf:latest
 
-RUN apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62  && \
-    echo "deb http://nginx.org/packages/debian/ jessie nginx" >> /etc/apt/sources.list  && apt-get update  && \
-    apt-get install --no-install-recommends --no-install-suggests -y       ca-certificates       \
-    nginx=${NGINX_VERSION}       nginx-module-xslt       nginx-module-geoip       nginx-module-image-filter       \
-    nginx-module-perl       nginx-module-njs       gettext-base  && rm -rf /var/lib/apt/lists/*  
+ENV NGINX_VERSION=1.11.13-1~jessie  
 
-RUN ln -sf /dev/stdout /var/log/nginx/access.log  && ln -sf /dev/stderr /var/log/nginx/error.log
+RUN set -e;  NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62;  \
+    found='';  for server in   ha.pool.sks-keyservers.net   \
+    hkp://keyserver.ubuntu.com:80 hkp://p80.pool.sks-keyservers.net:80 \
+    pgp.mit.edu  ; do   echo "Fetching GPG key $NGINX_GPGKEY from $server";  \
+    apt-key adv --keyserver "$server" --keyserver-options timeout=10 \
+    --recv-keys "$NGINX_GPGKEY" && found=yes && break;  done;  \
+    test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && \
+    exit 1;  exit 0
+
+RUN echo "deb http://nginx.org/packages/mainline/debian/ jessie nginx" \
+    >> /etc/apt/sources.list  && apt-get update  && apt-get install    \ 
+    --no-install-recommends --no-install-suggests -y   ca-certificates \
+    nginx=${NGINX_VERSION}       nginx-module-xslt  nginx-module-geoip \
+    nginx-module-image-filter       nginx-module-perl                  \
+    nginx-module-njs       gettext-base  && rm -rf /var/lib/apt/lists/*
+
+RUN ln -sf /dev/stdout /var/log/nginx/access.log  && ln -sf /dev/stderr \
+    /var/log/nginx/error.log
 
 RUN mkdir /etc/nginx/certs
 
 EXPOSE 443/tcp 80/tcp
 
-CMD "nginx -g 'daemon off;'"
+CMD nginx -g 'daemon off;'
           
 LABEL org.freenas.interactive=false \
       org.freenas.version=2 \
@@ -20,16 +33,17 @@ LABEL org.freenas.interactive=false \
       org.freenas.expose-ports-at-host=true \
       org.freenas.autostart=true \
       org.freenas.port-mappings=80:8080/tcp,443:8081/tcp \
-      org.freenas.volumes=[                                  \
+      org.freenas.volumes="[                                  \
       {                                        \
-            "name": "/usr/share/nginx/html",   \
-            "descr": "html content"            \
+            \"name\": \"/usr/share/nginx/html\",   \
+            \"descr\": \"html content\"            \
       },                                        \
       {                                        \
-            "name": "/etc/nginx/conf.d",       \
-            "descr": "Configuration Directory" 
-      },
+            \"name\": \"/etc/nginx/conf.d\",       \
+            \"descr\": \"Configuration Directory\" \
+      }, \
       {                                        \
-            "name": "/etc/nginx/certs",        \
-            "descr": "Certificate directory"   \
-      }
+            \"name\": \"/etc/nginx/certs\",        \
+            \"descr\": \"Certificate directory\"   \
+      } \
+      ]"
